### ISSUE TITLE
Error installing senzingdata and senzingapi packages

### ISSUE THREAD

**Issue by Racerx250** [Senzing/senzing-up#33]
When running senzing-up or senzing/yum, I encounter a 'more space needed on /opt/senzing/data filesystem' error.  This seems odd, since checking df -h shows that I have enough space. I also increase the disk image size docker, but this didn't change the result. Here's a snippet of the error:

![error](https://user-images.githubusercontent.com/35381083/100231829-294d7100-2eed-11eb-88b1-ef4b92e37284.PNG)

Running Ubuntu 20.04.1 running on Windows Subsystem for Linux. 

Thanks for the help and sorry if this is an error on my end!

**Comment by docktermj** [comment]
@ryanbasile Can you help on this one.  You've been working with Windows Subsystem for Linux.

**Comment by ryanbasile** [comment]
Hello. Are you using WSL or WSL2?

**Comment by Racerx250** [comment]
WSL!

**Comment by ryanbasile** [comment]
Hello. When using Docker I recommend using WSL2 because it has better integration with Docker Desktop, and containers run natively (see https://docs.docker.com/docker-for-windows/wsl/).

Are you able to install packages using `apt` directly on your Ubuntu install? See the [Quickstart Guide](https://senzing.zendesk.com/hc/en-us/articles/115002408867-Quickstart-Guide) for the Debian-based instructions.

Also, since you are using Ubuntu, you would want to use senzing/apt not senzing/yum.

Thank you

**Comment by Racerx250** [comment]
Got it! I'll update, then update soon

**Comment by Racerx250** [comment]
After switching to WSL2, it works! Thanks so much for the help.
